
import { GoogleGenAI, Modality, Part } from "@google/genai";

// Assume process.env.API_KEY is available
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

interface GeneratePosterParams {
  baseImage: {
    base64: string;
    mimeType: string;
  };
  logoImage?: {
    base64: string;
    mimeType: string;
  };
  prompt: string;
}

export const generatePoster = async ({
  baseImage,
  logoImage,
  prompt,
}: GeneratePosterParams): Promise<string> => {
  try {
    const parts: Part[] = [
      {
        inlineData: {
          data: baseImage.base64,
          mimeType: baseImage.mimeType,
        },
      },
      { text: prompt },
    ];

    if (logoImage) {
      parts.splice(1, 0, { // Insert logo after base image
        inlineData: {
          data: logoImage.base64,
          mimeType: logoImage.mimeType,
        },
      });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: parts,
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    
    throw new Error("No image was generated by the API. The prompt may have been blocked.");

  } catch (error) {
    console.error("Error generating poster:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate poster: ${error.message}`);
    }
    throw new Error("An unknown error occurred while generating the poster.");
  }
};

export const generateImageFromText = async (prompt: string, aspectRatio: '1:1' | '16:9' | '9:16'): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: aspectRatio,
        },
      });
  
      const generatedImage = response.generatedImages?.[0];

      if (generatedImage?.image?.imageBytes) {
        const base64ImageBytes: string = generatedImage.image.imageBytes;
        return `data:image/png;base64,${base64ImageBytes}`;
      }
    
    throw new Error("No image was generated by the API from the text prompt. The prompt may have been blocked.");

  } catch (error) {
    console.error("Error generating image from text:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image from text: ${error.message}`);
    }
    throw new Error("An unknown error occurred while generating the image from text.");
  }
};
